### PR TITLE
Format keyboard shortcuts according to OS conventions

### LINKED ISSUE #151: Format arrow shortcuts as arrow glyphs
If a shortcut has an arrow key, right now the text (e.g., "ArrowRight") is printed when the shortcut is formatted for display in https://github.com/jupyterlab/lumino/blob/4f2432290e874b040310d428593abe4afc336066/packages/commands/src/index.ts#L1133-L1165

A better convention, I think, is to replace arrows in the shortcut key with actual unicode arrow glyphs, i.e., "ArrowRight" with [unicode 2192](http://www.unicode-symbol.com/u/2192.html): →

### LINKED ISSUE #255: Change in arrow keys handling broke contract
## Description

#252 broke navigation with arrow keys, selecting cells with arrow keys and all other operations using arrow keys in JupyterLab (which for now is only visible on JupyterLab Desktop https://github.com/jupyterlab/jupyterlab-desktop/issues/320). This is because the addition of:

https://github.com/jupyterlab/lumino/blob/0f7378b62338868a53d0e6418d333f7e718d7411/packages/commands/src/index.ts#L1138-L1145

means that:

https://github.com/jupyterlab/lumino/blob/0f7378b62338868a53d0e6418d333f7e718d7411/packages/commands/src/index.ts#L1146-L1148

will not be executed for arrow keys, and all existing logic that relayed on arrow keys being there will fail.

## Reproduce

See https://github.com/jupyterlab/jupyterlab-desktop/issues/320.

## Expected behavior

1) this was released in a minor version, so we should fix it quickly; we should not change the contract in minor versions
2) arrow keys are not proper modifiers and should not be excluded from `key`

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #151
Fixes #255
Closes #256

This formats keyboard shortcuts to OS conventions on Windows and macOS. It reverts #252 and supersedes #256.

I checked with VoiceOver, and it appears that these glyphs are recognized correctly on Catalina when speaking shortcuts on menu items, etc. (i.e., the curvy arrow is correctly pronounced "return" when reading the keyboard shortcut). I pulled the Windows formatting conventions by looking at how custom keyboard shortcuts are formatted in Microsoft Word (IIRC), but it would be good to double-check those.

### CODE REVIEW

File: packages/commands/src/index.ts [hunk 1]
```diff
@@ -1492,6 +1429,45 @@ namespace Private {
...
+      return MAC_DISPLAY.hasOwnProperty(key) ? MAC_DISPLAY[key] : key;
+    } else {
+      return WIN_DISPLAY.hasOwnProperty(key) ? WIN_DISPLAY[key] : key;
+    }
+  }
+
+  const MAC_DISPLAY: { [key: string]: string } = {
+    Backspace: '⌫',
+    Tab: '⇥',
+    Enter: '↩',
```
Comment (krassowski) [inline packages/commands/src/index.ts:1443]: ⏎ might have a closer semantic meaning, but will often render as a less familiar icon

**Review by krassowski — APPROVED** [review]
Looks good to me, especially for the current use case of displaying the shortcuts as labels.

For better accessibility we could implement [aria-keyshortcuts](https://w3c.github.io/aria/#aria-keyshortcuts). I guess that would be another function taking the keystroke and returning the aria-label (or maybe `formatKeystroke` could return both `{label: string, aria: string}` in a future major version). If it makes sense I will open a new issue to track this accessibility improvement.

File: packages/commands/src/index.ts (hunk 1 above)
Comment (jasongrout) [reply packages/commands/src/index.ts:1443]: In VoiceOver, your character ⏎ is read as "return symbol", whereas the one in the PR (↩) is read as "return". I think the one in the PR is the official one to use.

**Comment by jasongrout** [comment]
> If it makes sense I will open a new issue to track this accessibility improvement.

+1

Huh, the Aria Shortcuts document seems to vindicate a decision we made about how shortcuts are specified that sometimes people call us out on as controversial or confusing:

> If the character used is determined by a modifier key, the author MUST specify the actual key used to generate the character, that is generated by the key, and not the resulting character. This convention enables the assistive technology to accurately convey what keys must be used to generate the shortcut. For example, on most U.S. English keyboards, the percent sign "%" can be input by pressing Shift+5. The correct way to specify this shortcut is "Shift+5". It is incorrect to specify "%" or "Shift+%".

**Comment by jasongrout** [comment]
Thanks for the review @krassowski!
